/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dvbviewertimerimport_dvbviewer_DVBViewerCOM */

#ifndef _Included_dvbviewertimerimport_dvbviewer_DVBViewerCOM
#define _Included_dvbviewertimerimport_dvbviewer_DVBViewerCOM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dvbviewertimerimport_dvbviewer_DVBViewerCOM
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dvbviewertimerimport_dvbviewer_DVBViewerCOM_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     dvbviewertimerimport_dvbviewer_DVBViewerCOM
 * Method:    connect
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_dvbviewertimerimport_dvbviewer_DVBViewerCOM_connect
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     dvbviewertimerimport_dvbviewer_DVBViewerCOM
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dvbviewertimerimport_dvbviewer_DVBViewerCOM_disconnect
  (JNIEnv *, jclass);

/*
 * Class:     dvbviewertimerimport_dvbviewer_DVBViewerCOM
 * Method:    getItems
 * Signature: ()[Ldvbviewertimerimport/dvbviewer/DVBViewerEntryCOM;
 */
JNIEXPORT jobjectArray JNICALL Java_dvbviewertimerimport_dvbviewer_DVBViewerCOM_getItems
  (JNIEnv *, jclass);

/*
 * Class:     dvbviewertimerimport_dvbviewer_DVBViewerCOM
 * Method:    setItems
 * Signature: ([Ldvbviewertimerimport/dvbviewer/DVBViewerEntryCOM;)V
 */
JNIEXPORT void JNICALL Java_dvbviewertimerimport_dvbviewer_DVBViewerCOM_setItems
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     dvbviewertimerimport_dvbviewer_DVBViewerCOM
 * Method:    getSetupValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dvbviewertimerimport_dvbviewer_DVBViewerCOM_getSetupValue
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     dvbviewertimerimport_dvbviewer_DVBViewerCOM
 * Method:    setCurrentChannel
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_dvbviewertimerimport_dvbviewer_DVBViewerCOM_setCurrentChannel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dvbviewertimerimport_dvbviewer_DVBViewerCOM
 * Method:    getCurrentChannelNo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dvbviewertimerimport_dvbviewer_DVBViewerCOM_getCurrentChannelNo
  (JNIEnv *, jclass);

/*
 * Class:     dvbviewertimerimport_dvbviewer_DVBViewerCOM
 * Method:    initLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dvbviewertimerimport_dvbviewer_DVBViewerCOM_initLog
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
